package com.alumnado.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CUESTIONARIO.
 */
public class Cuestionario {

    private Long id;
    private Long IdAlumno;
    private Long IdPregunta;
    private String Comentarios;

    public Cuestionario() {
    }

    public Cuestionario(Long id) {
        this.id = id;
    }

    public Cuestionario(Long id, Long IdAlumno, Long IdPregunta, String Comentarios) {
        this.id = id;
        this.IdAlumno = IdAlumno;
        this.IdPregunta = IdPregunta;
        this.Comentarios = Comentarios;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdAlumno() {
        return IdAlumno;
    }

    public void setIdAlumno(Long IdAlumno) {
        this.IdAlumno = IdAlumno;
    }

    public Long getIdPregunta() {
        return IdPregunta;
    }

    public void setIdPregunta(Long IdPregunta) {
        this.IdPregunta = IdPregunta;
    }

    public String getComentarios() {
        return Comentarios;
    }

    public void setComentarios(String Comentarios) {
        this.Comentarios = Comentarios;
    }

}
