package com.alumnado.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.alumnado.model.Cuestionario;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CUESTIONARIO.
*/
public class CuestionarioDao extends AbstractDao<Cuestionario, Long> {

    public static final String TABLENAME = "CUESTIONARIO";

    /**
     * Properties of entity Cuestionario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdAlumno = new Property(1, Long.class, "IdAlumno", false, "ID_ALUMNO");
        public final static Property IdPregunta = new Property(2, Long.class, "IdPregunta", false, "ID_PREGUNTA");
        public final static Property Comentarios = new Property(3, String.class, "Comentarios", false, "COMENTARIOS");
    };


    public CuestionarioDao(DaoConfig config) {
        super(config);
    }
    
    public CuestionarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CUESTIONARIO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_ALUMNO' INTEGER," + // 1: IdAlumno
                "'ID_PREGUNTA' INTEGER," + // 2: IdPregunta
                "'COMENTARIOS' TEXT);"); // 3: Comentarios
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CUESTIONARIO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Cuestionario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long IdAlumno = entity.getIdAlumno();
        if (IdAlumno != null) {
            stmt.bindLong(2, IdAlumno);
        }
 
        Long IdPregunta = entity.getIdPregunta();
        if (IdPregunta != null) {
            stmt.bindLong(3, IdPregunta);
        }
 
        String Comentarios = entity.getComentarios();
        if (Comentarios != null) {
            stmt.bindString(4, Comentarios);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Cuestionario readEntity(Cursor cursor, int offset) {
        Cuestionario entity = new Cuestionario( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // IdAlumno
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // IdPregunta
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // Comentarios
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Cuestionario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdAlumno(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIdPregunta(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setComentarios(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Cuestionario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Cuestionario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
