package com.alumnado.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ELEMENTO_LISTA.
 */
public class ElementoLista {

    private Long id;
    /** Not-null value. */
    private String Principal;
    private String Secundario;
    private String Terciario;
    private Long IdElemento;

    public ElementoLista() {
    }

    public ElementoLista(Long id) {
        this.id = id;
    }

    public ElementoLista(Long id, String Principal, String Secundario, String Terciario, Long IdElemento) {
        this.id = id;
        this.Principal = Principal;
        this.Secundario = Secundario;
        this.Terciario = Terciario;
        this.IdElemento = IdElemento;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPrincipal() {
        return Principal;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPrincipal(String Principal) {
        this.Principal = Principal;
    }

    public String getSecundario() {
        return Secundario;
    }

    public void setSecundario(String Secundario) {
        this.Secundario = Secundario;
    }

    public String getTerciario() {
        return Terciario;
    }

    public void setTerciario(String Terciario) {
        this.Terciario = Terciario;
    }

    public Long getIdElemento() {
        return IdElemento;
    }

    public void setIdElemento(Long IdElemento) {
        this.IdElemento = IdElemento;
    }

}
