package com.itrade.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEPOSITO.
 */
public class Deposito {

    private Long id;
    private Integer IdDeposito;
    private Integer IdUsuario;
    private Double Monto;
    private String Fecha;

    public Deposito() {
    }

    public Deposito(Long id) {
        this.id = id;
    }

    public Deposito(Long id, Integer IdDeposito, Integer IdUsuario, Double Monto, String Fecha) {
        this.id = id;
        this.IdDeposito = IdDeposito;
        this.IdUsuario = IdUsuario;
        this.Monto = Monto;
        this.Fecha = Fecha;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdDeposito() {
        return IdDeposito;
    }

    public void setIdDeposito(Integer IdDeposito) {
        this.IdDeposito = IdDeposito;
    }

    public Integer getIdUsuario() {
        return IdUsuario;
    }

    public void setIdUsuario(Integer IdUsuario) {
        this.IdUsuario = IdUsuario;
    }

    public Double getMonto() {
        return Monto;
    }

    public void setMonto(Double Monto) {
        this.Monto = Monto;
    }

    public String getFecha() {
        return Fecha;
    }

    public void setFecha(String Fecha) {
        this.Fecha = Fecha;
    }

}
