package com.itrade.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table META.
 */
public class Meta {

    private Long id;
    private Long IdMeta;
    private Double Suma;
    private String Fechini;
    private String Fechafin;
    private Double Meta;
    private String Nombre;

    public Meta() {
    }

    public Meta(Long id) {
        this.id = id;
    }

    public Meta(Long id, Long IdMeta, Double Suma, String Fechini, String Fechafin, Double Meta, String Nombre) {
        this.id = id;
        this.IdMeta = IdMeta;
        this.Suma = Suma;
        this.Fechini = Fechini;
        this.Fechafin = Fechafin;
        this.Meta = Meta;
        this.Nombre = Nombre;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdMeta() {
        return IdMeta;
    }

    public void setIdMeta(Long IdMeta) {
        this.IdMeta = IdMeta;
    }

    public Double getSuma() {
        return Suma;
    }

    public void setSuma(Double Suma) {
        this.Suma = Suma;
    }

    public String getFechini() {
        return Fechini;
    }

    public void setFechini(String Fechini) {
        this.Fechini = Fechini;
    }

    public String getFechafin() {
        return Fechafin;
    }

    public void setFechafin(String Fechafin) {
        this.Fechafin = Fechafin;
    }

    public Double getMeta() {
        return Meta;
    }

    public void setMeta(Double Meta) {
        this.Meta = Meta;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

}
