package com.itrade.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PEDIDO.
 */
public class Pedido {

    private Long id;
    private Long IdPedido;
    private Integer IdCliente;
    private Integer IdEstadoPedido;
    private Integer CheckIn;
    private java.util.Date FechaPedido;
    private java.util.Date FechaCobranza;
    private Double MontoSinIGV;
    private Double IGV;
    private Double MontoTotalPedido;
    private Double MontoTotalCobrado;
    private String NumVoucher;
    private Double MontoTotal;

    public Pedido() {
    }

    public Pedido(Long id) {
        this.id = id;
    }

    public Pedido(Long id, Long IdPedido, Integer IdCliente, Integer IdEstadoPedido, Integer CheckIn, java.util.Date FechaPedido, java.util.Date FechaCobranza, Double MontoSinIGV, Double IGV, Double MontoTotalPedido, Double MontoTotalCobrado, String NumVoucher, Double MontoTotal) {
        this.id = id;
        this.IdPedido = IdPedido;
        this.IdCliente = IdCliente;
        this.IdEstadoPedido = IdEstadoPedido;
        this.CheckIn = CheckIn;
        this.FechaPedido = FechaPedido;
        this.FechaCobranza = FechaCobranza;
        this.MontoSinIGV = MontoSinIGV;
        this.IGV = IGV;
        this.MontoTotalPedido = MontoTotalPedido;
        this.MontoTotalCobrado = MontoTotalCobrado;
        this.NumVoucher = NumVoucher;
        this.MontoTotal = MontoTotal;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdPedido() {
        return IdPedido;
    }

    public void setIdPedido(Long IdPedido) {
        this.IdPedido = IdPedido;
    }

    public Integer getIdCliente() {
        return IdCliente;
    }

    public void setIdCliente(Integer IdCliente) {
        this.IdCliente = IdCliente;
    }

    public Integer getIdEstadoPedido() {
        return IdEstadoPedido;
    }

    public void setIdEstadoPedido(Integer IdEstadoPedido) {
        this.IdEstadoPedido = IdEstadoPedido;
    }

    public Integer getCheckIn() {
        return CheckIn;
    }

    public void setCheckIn(Integer CheckIn) {
        this.CheckIn = CheckIn;
    }

    public java.util.Date getFechaPedido() {
        return FechaPedido;
    }

    public void setFechaPedido(java.util.Date FechaPedido) {
        this.FechaPedido = FechaPedido;
    }

    public java.util.Date getFechaCobranza() {
        return FechaCobranza;
    }

    public void setFechaCobranza(java.util.Date FechaCobranza) {
        this.FechaCobranza = FechaCobranza;
    }

    public Double getMontoSinIGV() {
        return MontoSinIGV;
    }

    public void setMontoSinIGV(Double MontoSinIGV) {
        this.MontoSinIGV = MontoSinIGV;
    }

    public Double getIGV() {
        return IGV;
    }

    public void setIGV(Double IGV) {
        this.IGV = IGV;
    }

    public Double getMontoTotalPedido() {
        return MontoTotalPedido;
    }

    public void setMontoTotalPedido(Double MontoTotalPedido) {
        this.MontoTotalPedido = MontoTotalPedido;
    }

    public Double getMontoTotalCobrado() {
        return MontoTotalCobrado;
    }

    public void setMontoTotalCobrado(Double MontoTotalCobrado) {
        this.MontoTotalCobrado = MontoTotalCobrado;
    }

    public String getNumVoucher() {
        return NumVoucher;
    }

    public void setNumVoucher(String NumVoucher) {
        this.NumVoucher = NumVoucher;
    }

    public Double getMontoTotal() {
        return MontoTotal;
    }

    public void setMontoTotal(Double MontoTotal) {
        this.MontoTotal = MontoTotal;
    }

}
