package com.itrade.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.itrade.model.Persona;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PERSONA.
*/
public class PersonaDao extends AbstractDao<Persona, Long> {

    public static final String TABLENAME = "PERSONA";

    /**
     * Properties of entity Persona.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "Nombre", false, "NOMBRE");
        public final static Property ApePaterno = new Property(2, String.class, "ApePaterno", false, "APE_PATERNO");
        public final static Property ApeMaterno = new Property(3, String.class, "ApeMaterno", false, "APE_MATERNO");
        public final static Property DNI = new Property(4, String.class, "DNI", false, "DNI");
        public final static Property FechNac = new Property(5, java.util.Date.class, "FechNac", false, "FECH_NAC");
        public final static Property Telefono = new Property(6, String.class, "Telefono", false, "TELEFONO");
        public final static Property Email = new Property(7, String.class, "Email", false, "EMAIL");
        public final static Property Activo = new Property(8, String.class, "Activo", false, "ACTIVO");
    };


    public PersonaDao(DaoConfig config) {
        super(config);
    }
    
    public PersonaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PERSONA' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NOMBRE' TEXT NOT NULL ," + // 1: Nombre
                "'APE_PATERNO' TEXT," + // 2: ApePaterno
                "'APE_MATERNO' TEXT," + // 3: ApeMaterno
                "'DNI' TEXT," + // 4: DNI
                "'FECH_NAC' INTEGER," + // 5: FechNac
                "'TELEFONO' TEXT," + // 6: Telefono
                "'EMAIL' TEXT," + // 7: Email
                "'ACTIVO' TEXT);"); // 8: Activo
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PERSONA'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Persona entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombre());
 
        String ApePaterno = entity.getApePaterno();
        if (ApePaterno != null) {
            stmt.bindString(3, ApePaterno);
        }
 
        String ApeMaterno = entity.getApeMaterno();
        if (ApeMaterno != null) {
            stmt.bindString(4, ApeMaterno);
        }
 
        String DNI = entity.getDNI();
        if (DNI != null) {
            stmt.bindString(5, DNI);
        }
 
        java.util.Date FechNac = entity.getFechNac();
        if (FechNac != null) {
            stmt.bindLong(6, FechNac.getTime());
        }
 
        String Telefono = entity.getTelefono();
        if (Telefono != null) {
            stmt.bindString(7, Telefono);
        }
 
        String Email = entity.getEmail();
        if (Email != null) {
            stmt.bindString(8, Email);
        }
 
        String Activo = entity.getActivo();
        if (Activo != null) {
            stmt.bindString(9, Activo);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Persona readEntity(Cursor cursor, int offset) {
        Persona entity = new Persona( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // Nombre
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ApePaterno
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ApeMaterno
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // DNI
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // FechNac
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Telefono
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Email
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // Activo
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Persona entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.getString(offset + 1));
        entity.setApePaterno(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setApeMaterno(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDNI(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFechNac(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setTelefono(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEmail(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setActivo(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Persona entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Persona entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
