package com.alumnado.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ALUMNO.
 */
public class Alumno {

    private Long id;
    private Long IdAlumno;
    private String Nombres;
    private String ApePaterno;
    private String ApeMaterno;

    public Alumno() {
    }

    public Alumno(Long id) {
        this.id = id;
    }

    public Alumno(Long id, Long IdAlumno, String Nombres, String ApePaterno, String ApeMaterno) {
        this.id = id;
        this.IdAlumno = IdAlumno;
        this.Nombres = Nombres;
        this.ApePaterno = ApePaterno;
        this.ApeMaterno = ApeMaterno;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdAlumno() {
        return IdAlumno;
    }

    public void setIdAlumno(Long IdAlumno) {
        this.IdAlumno = IdAlumno;
    }

    public String getNombres() {
        return Nombres;
    }

    public void setNombres(String Nombres) {
        this.Nombres = Nombres;
    }

    public String getApePaterno() {
        return ApePaterno;
    }

    public void setApePaterno(String ApePaterno) {
        this.ApePaterno = ApePaterno;
    }

    public String getApeMaterno() {
        return ApeMaterno;
    }

    public void setApeMaterno(String ApeMaterno) {
        this.ApeMaterno = ApeMaterno;
    }

}
