package com.alumnado.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.alumnado.model.ElementoLista;
import com.alumnado.model.Alumno;
import com.alumnado.model.Pregunta;
import com.alumnado.model.Cuestionario;

import com.alumnado.model.ElementoListaDao;
import com.alumnado.model.AlumnoDao;
import com.alumnado.model.PreguntaDao;
import com.alumnado.model.CuestionarioDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig elementoListaDaoConfig;
    private final DaoConfig alumnoDaoConfig;
    private final DaoConfig preguntaDaoConfig;
    private final DaoConfig cuestionarioDaoConfig;

    private final ElementoListaDao elementoListaDao;
    private final AlumnoDao alumnoDao;
    private final PreguntaDao preguntaDao;
    private final CuestionarioDao cuestionarioDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        elementoListaDaoConfig = daoConfigMap.get(ElementoListaDao.class).clone();
        elementoListaDaoConfig.initIdentityScope(type);

        alumnoDaoConfig = daoConfigMap.get(AlumnoDao.class).clone();
        alumnoDaoConfig.initIdentityScope(type);

        preguntaDaoConfig = daoConfigMap.get(PreguntaDao.class).clone();
        preguntaDaoConfig.initIdentityScope(type);

        cuestionarioDaoConfig = daoConfigMap.get(CuestionarioDao.class).clone();
        cuestionarioDaoConfig.initIdentityScope(type);

        elementoListaDao = new ElementoListaDao(elementoListaDaoConfig, this);
        alumnoDao = new AlumnoDao(alumnoDaoConfig, this);
        preguntaDao = new PreguntaDao(preguntaDaoConfig, this);
        cuestionarioDao = new CuestionarioDao(cuestionarioDaoConfig, this);

        registerDao(ElementoLista.class, elementoListaDao);
        registerDao(Alumno.class, alumnoDao);
        registerDao(Pregunta.class, preguntaDao);
        registerDao(Cuestionario.class, cuestionarioDao);
    }
    
    public void clear() {
        elementoListaDaoConfig.getIdentityScope().clear();
        alumnoDaoConfig.getIdentityScope().clear();
        preguntaDaoConfig.getIdentityScope().clear();
        cuestionarioDaoConfig.getIdentityScope().clear();
    }

    public ElementoListaDao getElementoListaDao() {
        return elementoListaDao;
    }

    public AlumnoDao getAlumnoDao() {
        return alumnoDao;
    }

    public PreguntaDao getPreguntaDao() {
        return preguntaDao;
    }

    public CuestionarioDao getCuestionarioDao() {
        return cuestionarioDao;
    }

}
