package com.alumnado.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PREGUNTA.
 */
public class Pregunta {

    private Long id;
    private Long IdPregunta;
    private String Formula;

    public Pregunta() {
    }

    public Pregunta(Long id) {
        this.id = id;
    }

    public Pregunta(Long id, Long IdPregunta, String Formula) {
        this.id = id;
        this.IdPregunta = IdPregunta;
        this.Formula = Formula;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdPregunta() {
        return IdPregunta;
    }

    public void setIdPregunta(Long IdPregunta) {
        this.IdPregunta = IdPregunta;
    }

    public String getFormula() {
        return Formula;
    }

    public void setFormula(String Formula) {
        this.Formula = Formula;
    }

}
