package com.itrade.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EVENTO.
 */
public class Evento {

    private Long id;
    private Integer IdEvento;
    private String Creador;
    private String Asunto;
    private String Lugar;
    private String Descripcion;
    private String Fecha;
    private String HoraInicio;
    private String HoraFin;

    public Evento() {
    }

    public Evento(Long id) {
        this.id = id;
    }

    public Evento(Long id, Integer IdEvento, String Creador, String Asunto, String Lugar, String Descripcion, String Fecha, String HoraInicio, String HoraFin) {
        this.id = id;
        this.IdEvento = IdEvento;
        this.Creador = Creador;
        this.Asunto = Asunto;
        this.Lugar = Lugar;
        this.Descripcion = Descripcion;
        this.Fecha = Fecha;
        this.HoraInicio = HoraInicio;
        this.HoraFin = HoraFin;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdEvento() {
        return IdEvento;
    }

    public void setIdEvento(Integer IdEvento) {
        this.IdEvento = IdEvento;
    }

    public String getCreador() {
        return Creador;
    }

    public void setCreador(String Creador) {
        this.Creador = Creador;
    }

    public String getAsunto() {
        return Asunto;
    }

    public void setAsunto(String Asunto) {
        this.Asunto = Asunto;
    }

    public String getLugar() {
        return Lugar;
    }

    public void setLugar(String Lugar) {
        this.Lugar = Lugar;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public String getFecha() {
        return Fecha;
    }

    public void setFecha(String Fecha) {
        this.Fecha = Fecha;
    }

    public String getHoraInicio() {
        return HoraInicio;
    }

    public void setHoraInicio(String HoraInicio) {
        this.HoraInicio = HoraInicio;
    }

    public String getHoraFin() {
        return HoraFin;
    }

    public void setHoraFin(String HoraFin) {
        this.HoraFin = HoraFin;
    }

}
