package com.itrade.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.itrade.model.Notificacion;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table NOTIFICACION.
*/
public class NotificacionDao extends AbstractDao<Notificacion, Long> {

    public static final String TABLENAME = "NOTIFICACION";

    /**
     * Properties of entity Notificacion.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdNotificacion = new Property(1, Integer.class, "IdNotificacion", false, "ID_NOTIFICACION");
        public final static Property IdUsuario = new Property(2, Integer.class, "IdUsuario", false, "ID_USUARIO");
        public final static Property Fecha = new Property(3, String.class, "Fecha", false, "FECHA");
    };


    public NotificacionDao(DaoConfig config) {
        super(config);
    }
    
    public NotificacionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'NOTIFICACION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_NOTIFICACION' INTEGER," + // 1: IdNotificacion
                "'ID_USUARIO' INTEGER," + // 2: IdUsuario
                "'FECHA' TEXT);"); // 3: Fecha
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'NOTIFICACION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Notificacion entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer IdNotificacion = entity.getIdNotificacion();
        if (IdNotificacion != null) {
            stmt.bindLong(2, IdNotificacion);
        }
 
        Integer IdUsuario = entity.getIdUsuario();
        if (IdUsuario != null) {
            stmt.bindLong(3, IdUsuario);
        }
 
        String Fecha = entity.getFecha();
        if (Fecha != null) {
            stmt.bindString(4, Fecha);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Notificacion readEntity(Cursor cursor, int offset) {
        Notificacion entity = new Notificacion( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // IdNotificacion
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // IdUsuario
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // Fecha
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Notificacion entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdNotificacion(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setIdUsuario(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setFecha(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Notificacion entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Notificacion entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
