package com.itrade.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PEDIDO_LINEA.
 */
public class PedidoLinea {

    private Long id;
    private Long IdPedido;
    private Long IdPedidoLinea;
    private Integer IdProducto;
    private Double MontoLinea;
    private Double Precio;
    private Integer Cantidad;
    private String NombreProducto;
    private String Marca;
    private String Categoria;

    public PedidoLinea() {
    }

    public PedidoLinea(Long id) {
        this.id = id;
    }

    public PedidoLinea(Long id, Long IdPedido, Long IdPedidoLinea, Integer IdProducto, Double MontoLinea, Double Precio, Integer Cantidad, String NombreProducto, String Marca, String Categoria) {
        this.id = id;
        this.IdPedido = IdPedido;
        this.IdPedidoLinea = IdPedidoLinea;
        this.IdProducto = IdProducto;
        this.MontoLinea = MontoLinea;
        this.Precio = Precio;
        this.Cantidad = Cantidad;
        this.NombreProducto = NombreProducto;
        this.Marca = Marca;
        this.Categoria = Categoria;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdPedido() {
        return IdPedido;
    }

    public void setIdPedido(Long IdPedido) {
        this.IdPedido = IdPedido;
    }

    public Long getIdPedidoLinea() {
        return IdPedidoLinea;
    }

    public void setIdPedidoLinea(Long IdPedidoLinea) {
        this.IdPedidoLinea = IdPedidoLinea;
    }

    public Integer getIdProducto() {
        return IdProducto;
    }

    public void setIdProducto(Integer IdProducto) {
        this.IdProducto = IdProducto;
    }

    public Double getMontoLinea() {
        return MontoLinea;
    }

    public void setMontoLinea(Double MontoLinea) {
        this.MontoLinea = MontoLinea;
    }

    public Double getPrecio() {
        return Precio;
    }

    public void setPrecio(Double Precio) {
        this.Precio = Precio;
    }

    public Integer getCantidad() {
        return Cantidad;
    }

    public void setCantidad(Integer Cantidad) {
        this.Cantidad = Cantidad;
    }

    public String getNombreProducto() {
        return NombreProducto;
    }

    public void setNombreProducto(String NombreProducto) {
        this.NombreProducto = NombreProducto;
    }

    public String getMarca() {
        return Marca;
    }

    public void setMarca(String Marca) {
        this.Marca = Marca;
    }

    public String getCategoria() {
        return Categoria;
    }

    public void setCategoria(String Categoria) {
        this.Categoria = Categoria;
    }

}
