package com.itrade.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.itrade.model.Pedido;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PEDIDO.
*/
public class PedidoDao extends AbstractDao<Pedido, Long> {

    public static final String TABLENAME = "PEDIDO";

    /**
     * Properties of entity Pedido.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property IdPedido = new Property(1, Long.class, "IdPedido", false, "ID_PEDIDO");
        public final static Property IdCliente = new Property(2, Integer.class, "IdCliente", false, "ID_CLIENTE");
        public final static Property IdEstadoPedido = new Property(3, Integer.class, "IdEstadoPedido", false, "ID_ESTADO_PEDIDO");
        public final static Property CheckIn = new Property(4, Integer.class, "CheckIn", false, "CHECK_IN");
        public final static Property FechaPedido = new Property(5, java.util.Date.class, "FechaPedido", false, "FECHA_PEDIDO");
        public final static Property FechaCobranza = new Property(6, java.util.Date.class, "FechaCobranza", false, "FECHA_COBRANZA");
        public final static Property MontoSinIGV = new Property(7, Double.class, "MontoSinIGV", false, "MONTO_SIN_IGV");
        public final static Property IGV = new Property(8, Double.class, "IGV", false, "IGV");
        public final static Property MontoTotalPedido = new Property(9, Double.class, "MontoTotalPedido", false, "MONTO_TOTAL_PEDIDO");
        public final static Property MontoTotalCobrado = new Property(10, Double.class, "MontoTotalCobrado", false, "MONTO_TOTAL_COBRADO");
        public final static Property NumVoucher = new Property(11, String.class, "NumVoucher", false, "NUM_VOUCHER");
        public final static Property MontoTotal = new Property(12, Double.class, "MontoTotal", false, "MONTO_TOTAL");
    };


    public PedidoDao(DaoConfig config) {
        super(config);
    }
    
    public PedidoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PEDIDO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ID_PEDIDO' INTEGER," + // 1: IdPedido
                "'ID_CLIENTE' INTEGER," + // 2: IdCliente
                "'ID_ESTADO_PEDIDO' INTEGER," + // 3: IdEstadoPedido
                "'CHECK_IN' INTEGER," + // 4: CheckIn
                "'FECHA_PEDIDO' INTEGER," + // 5: FechaPedido
                "'FECHA_COBRANZA' INTEGER," + // 6: FechaCobranza
                "'MONTO_SIN_IGV' REAL," + // 7: MontoSinIGV
                "'IGV' REAL," + // 8: IGV
                "'MONTO_TOTAL_PEDIDO' REAL," + // 9: MontoTotalPedido
                "'MONTO_TOTAL_COBRADO' REAL," + // 10: MontoTotalCobrado
                "'NUM_VOUCHER' TEXT," + // 11: NumVoucher
                "'MONTO_TOTAL' REAL);"); // 12: MontoTotal
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PEDIDO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Pedido entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long IdPedido = entity.getIdPedido();
        if (IdPedido != null) {
            stmt.bindLong(2, IdPedido);
        }
 
        Integer IdCliente = entity.getIdCliente();
        if (IdCliente != null) {
            stmt.bindLong(3, IdCliente);
        }
 
        Integer IdEstadoPedido = entity.getIdEstadoPedido();
        if (IdEstadoPedido != null) {
            stmt.bindLong(4, IdEstadoPedido);
        }
 
        Integer CheckIn = entity.getCheckIn();
        if (CheckIn != null) {
            stmt.bindLong(5, CheckIn);
        }
 
        java.util.Date FechaPedido = entity.getFechaPedido();
        if (FechaPedido != null) {
            stmt.bindLong(6, FechaPedido.getTime());
        }
 
        java.util.Date FechaCobranza = entity.getFechaCobranza();
        if (FechaCobranza != null) {
            stmt.bindLong(7, FechaCobranza.getTime());
        }
 
        Double MontoSinIGV = entity.getMontoSinIGV();
        if (MontoSinIGV != null) {
            stmt.bindDouble(8, MontoSinIGV);
        }
 
        Double IGV = entity.getIGV();
        if (IGV != null) {
            stmt.bindDouble(9, IGV);
        }
 
        Double MontoTotalPedido = entity.getMontoTotalPedido();
        if (MontoTotalPedido != null) {
            stmt.bindDouble(10, MontoTotalPedido);
        }
 
        Double MontoTotalCobrado = entity.getMontoTotalCobrado();
        if (MontoTotalCobrado != null) {
            stmt.bindDouble(11, MontoTotalCobrado);
        }
 
        String NumVoucher = entity.getNumVoucher();
        if (NumVoucher != null) {
            stmt.bindString(12, NumVoucher);
        }
 
        Double MontoTotal = entity.getMontoTotal();
        if (MontoTotal != null) {
            stmt.bindDouble(13, MontoTotal);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Pedido readEntity(Cursor cursor, int offset) {
        Pedido entity = new Pedido( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // IdPedido
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // IdCliente
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // IdEstadoPedido
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // CheckIn
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // FechaPedido
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)), // FechaCobranza
            cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7), // MontoSinIGV
            cursor.isNull(offset + 8) ? null : cursor.getDouble(offset + 8), // IGV
            cursor.isNull(offset + 9) ? null : cursor.getDouble(offset + 9), // MontoTotalPedido
            cursor.isNull(offset + 10) ? null : cursor.getDouble(offset + 10), // MontoTotalCobrado
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // NumVoucher
            cursor.isNull(offset + 12) ? null : cursor.getDouble(offset + 12) // MontoTotal
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Pedido entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdPedido(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIdCliente(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setIdEstadoPedido(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setCheckIn(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setFechaPedido(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setFechaCobranza(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
        entity.setMontoSinIGV(cursor.isNull(offset + 7) ? null : cursor.getDouble(offset + 7));
        entity.setIGV(cursor.isNull(offset + 8) ? null : cursor.getDouble(offset + 8));
        entity.setMontoTotalPedido(cursor.isNull(offset + 9) ? null : cursor.getDouble(offset + 9));
        entity.setMontoTotalCobrado(cursor.isNull(offset + 10) ? null : cursor.getDouble(offset + 10));
        entity.setNumVoucher(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setMontoTotal(cursor.isNull(offset + 12) ? null : cursor.getDouble(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Pedido entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Pedido entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
