package com.itrade.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PRODUCTO.
 */
public class Producto {

    private Long id;
    private int IdProducto;
    private String Descripcion;
    private Double Precio;
    private Integer Stock;
    private String Activo;
    private Integer IdCategoria;
    private Integer IdMarca;

    public Producto() {
    }

    public Producto(Long id) {
        this.id = id;
    }

    public Producto(Long id, int IdProducto, String Descripcion, Double Precio, Integer Stock, String Activo, Integer IdCategoria, Integer IdMarca) {
        this.id = id;
        this.IdProducto = IdProducto;
        this.Descripcion = Descripcion;
        this.Precio = Precio;
        this.Stock = Stock;
        this.Activo = Activo;
        this.IdCategoria = IdCategoria;
        this.IdMarca = IdMarca;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getIdProducto() {
        return IdProducto;
    }

    public void setIdProducto(int IdProducto) {
        this.IdProducto = IdProducto;
    }

    public String getDescripcion() {
        return Descripcion;
    }

    public void setDescripcion(String Descripcion) {
        this.Descripcion = Descripcion;
    }

    public Double getPrecio() {
        return Precio;
    }

    public void setPrecio(Double Precio) {
        this.Precio = Precio;
    }

    public Integer getStock() {
        return Stock;
    }

    public void setStock(Integer Stock) {
        this.Stock = Stock;
    }

    public String getActivo() {
        return Activo;
    }

    public void setActivo(String Activo) {
        this.Activo = Activo;
    }

    public Integer getIdCategoria() {
        return IdCategoria;
    }

    public void setIdCategoria(Integer IdCategoria) {
        this.IdCategoria = IdCategoria;
    }

    public Integer getIdMarca() {
        return IdMarca;
    }

    public void setIdMarca(Integer IdMarca) {
        this.IdMarca = IdMarca;
    }

}
