package com.itrade.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.itrade.model.Usuario;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table USUARIO.
*/
public class UsuarioDao extends AbstractDao<Usuario, Long> {

    public static final String TABLENAME = "USUARIO";

    /**
     * Properties of entity Usuario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Nombre = new Property(1, String.class, "Nombre", false, "NOMBRE");
        public final static Property Password = new Property(2, String.class, "Password", false, "PASSWORD");
        public final static Property IdPerfil = new Property(3, Integer.class, "IdPerfil", false, "ID_PERFIL");
        public final static Property IdPersona = new Property(4, Integer.class, "IdPersona", false, "ID_PERSONA");
        public final static Property Activo = new Property(5, String.class, "Activo", false, "ACTIVO");
        public final static Property IdJerarquia = new Property(6, Integer.class, "IdJerarquia", false, "ID_JERARQUIA");
        public final static Property IdZona = new Property(7, Integer.class, "IdZona", false, "ID_ZONA");
        public final static Property IdDistrito = new Property(8, Integer.class, "IdDistrito", false, "ID_DISTRITO");
        public final static Property IdCiudad = new Property(9, Integer.class, "IdCiudad", false, "ID_CIUDAD");
        public final static Property IdPais = new Property(10, Integer.class, "IdPais", false, "ID_PAIS");
    };


    public UsuarioDao(DaoConfig config) {
        super(config);
    }
    
    public UsuarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'USUARIO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NOMBRE' TEXT NOT NULL ," + // 1: Nombre
                "'PASSWORD' TEXT," + // 2: Password
                "'ID_PERFIL' INTEGER," + // 3: IdPerfil
                "'ID_PERSONA' INTEGER," + // 4: IdPersona
                "'ACTIVO' TEXT," + // 5: Activo
                "'ID_JERARQUIA' INTEGER," + // 6: IdJerarquia
                "'ID_ZONA' INTEGER," + // 7: IdZona
                "'ID_DISTRITO' INTEGER," + // 8: IdDistrito
                "'ID_CIUDAD' INTEGER," + // 9: IdCiudad
                "'ID_PAIS' INTEGER);"); // 10: IdPais
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'USUARIO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Usuario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getNombre());
 
        String Password = entity.getPassword();
        if (Password != null) {
            stmt.bindString(3, Password);
        }
 
        Integer IdPerfil = entity.getIdPerfil();
        if (IdPerfil != null) {
            stmt.bindLong(4, IdPerfil);
        }
 
        Integer IdPersona = entity.getIdPersona();
        if (IdPersona != null) {
            stmt.bindLong(5, IdPersona);
        }
 
        String Activo = entity.getActivo();
        if (Activo != null) {
            stmt.bindString(6, Activo);
        }
 
        Integer IdJerarquia = entity.getIdJerarquia();
        if (IdJerarquia != null) {
            stmt.bindLong(7, IdJerarquia);
        }
 
        Integer IdZona = entity.getIdZona();
        if (IdZona != null) {
            stmt.bindLong(8, IdZona);
        }
 
        Integer IdDistrito = entity.getIdDistrito();
        if (IdDistrito != null) {
            stmt.bindLong(9, IdDistrito);
        }
 
        Integer IdCiudad = entity.getIdCiudad();
        if (IdCiudad != null) {
            stmt.bindLong(10, IdCiudad);
        }
 
        Integer IdPais = entity.getIdPais();
        if (IdPais != null) {
            stmt.bindLong(11, IdPais);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Usuario readEntity(Cursor cursor, int offset) {
        Usuario entity = new Usuario( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // Nombre
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // Password
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // IdPerfil
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // IdPersona
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // Activo
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // IdJerarquia
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // IdZona
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // IdDistrito
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // IdCiudad
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10) // IdPais
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Usuario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre(cursor.getString(offset + 1));
        entity.setPassword(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdPerfil(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setIdPersona(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setActivo(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIdJerarquia(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setIdZona(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setIdDistrito(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setIdCiudad(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setIdPais(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Usuario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Usuario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
