package com.itrade.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USUARIO.
 */
public class Usuario {

    private Long id;
    private Integer IdUsuario;
    private String Username;
    private String Nombre;
    private String ApePaterno;
    private String ApeMaterno;
    private String Password;
    private Integer IdPerfil;
    private Integer IdPersona;
    private String Activo;
    private Integer IdJerarquia;
    private Integer IdZona;
    private Integer IdDistrito;
    private Integer IdCiudad;
    private Integer IdPais;

    public Usuario() {
    }

    public Usuario(Long id) {
        this.id = id;
    }

    public Usuario(Long id, Integer IdUsuario, String Username, String Nombre, String ApePaterno, String ApeMaterno, String Password, Integer IdPerfil, Integer IdPersona, String Activo, Integer IdJerarquia, Integer IdZona, Integer IdDistrito, Integer IdCiudad, Integer IdPais) {
        this.id = id;
        this.IdUsuario = IdUsuario;
        this.Username = Username;
        this.Nombre = Nombre;
        this.ApePaterno = ApePaterno;
        this.ApeMaterno = ApeMaterno;
        this.Password = Password;
        this.IdPerfil = IdPerfil;
        this.IdPersona = IdPersona;
        this.Activo = Activo;
        this.IdJerarquia = IdJerarquia;
        this.IdZona = IdZona;
        this.IdDistrito = IdDistrito;
        this.IdCiudad = IdCiudad;
        this.IdPais = IdPais;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getIdUsuario() {
        return IdUsuario;
    }

    public void setIdUsuario(Integer IdUsuario) {
        this.IdUsuario = IdUsuario;
    }

    public String getUsername() {
        return Username;
    }

    public void setUsername(String Username) {
        this.Username = Username;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public String getApePaterno() {
        return ApePaterno;
    }

    public void setApePaterno(String ApePaterno) {
        this.ApePaterno = ApePaterno;
    }

    public String getApeMaterno() {
        return ApeMaterno;
    }

    public void setApeMaterno(String ApeMaterno) {
        this.ApeMaterno = ApeMaterno;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public Integer getIdPerfil() {
        return IdPerfil;
    }

    public void setIdPerfil(Integer IdPerfil) {
        this.IdPerfil = IdPerfil;
    }

    public Integer getIdPersona() {
        return IdPersona;
    }

    public void setIdPersona(Integer IdPersona) {
        this.IdPersona = IdPersona;
    }

    public String getActivo() {
        return Activo;
    }

    public void setActivo(String Activo) {
        this.Activo = Activo;
    }

    public Integer getIdJerarquia() {
        return IdJerarquia;
    }

    public void setIdJerarquia(Integer IdJerarquia) {
        this.IdJerarquia = IdJerarquia;
    }

    public Integer getIdZona() {
        return IdZona;
    }

    public void setIdZona(Integer IdZona) {
        this.IdZona = IdZona;
    }

    public Integer getIdDistrito() {
        return IdDistrito;
    }

    public void setIdDistrito(Integer IdDistrito) {
        this.IdDistrito = IdDistrito;
    }

    public Integer getIdCiudad() {
        return IdCiudad;
    }

    public void setIdCiudad(Integer IdCiudad) {
        this.IdCiudad = IdCiudad;
    }

    public Integer getIdPais() {
        return IdPais;
    }

    public void setIdPais(Integer IdPais) {
        this.IdPais = IdPais;
    }

}
